spring.application.name=Bemole_API
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_bemole?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=itson
spring.jpa.hibernate.ddl-auto=update