spring.application.name=Bemole_API
server.port=8081

spring.web.error.include-stacktrace=never
spring.web.error.include-message=never
spring.web.error.include-binding-errors=never
spring.web.error.include-exception=false

security.jwt.secret=${JWT_SECRET}
security.jwt.expiration=3600000

spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_bemole?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=itson
spring.jpa.hibernate.ddl-auto=update

